# This is a basic workflow to help you get started with Actions

name: check-alive

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  checkthing:
    runs-on: ubuntu-latest
    steps:
      - name: check health
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://morning-shore-02726.herokuapp.com/health
          max-attempts: 3 
          retry-delay: 5s 
